import { writeFile } from 'fs/promises';
import { existsSync } from 'fs';
import slugify from 'slugify';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { questionBank } from '../src/data/questionBank.js';
import { SCENARIOS } from '../src/data/numberData.js';
import {
  wonderNarration,
  getStoryNarration,
  simulateStationNarration,
  simulateFeedbackNarration,
  praisePhrases,
  playPhaseNarration,
  reflectQuestionNarration
} from '../src/utils/narration.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const AUDIO_DIR = join(__dirname, '..', 'public', 'assets', 'audio');
const AUDIO_MAP_PATH = join(__dirname, '..', 'src', 'utils', 'audioMap.js');

function buildPhrases() {
  const phrases = [];
  const seen = new Set();
  const add = (text, style) => {
    if (!text || seen.has(text)) return;
    seen.add(text);
    phrases.push({ text, style });
  };

  wonderNarration().forEach(t => add(t, 'question'));
  getStoryNarration().forEach(t => add(t, 'statement'));
  simulateStationNarration().forEach(t => add(t, 'instruction'));
  simulateFeedbackNarration().forEach(t => add(t, 'encouragement'));
  praisePhrases().forEach(t => add(t, 'celebration'));
  playPhaseNarration().forEach(t => add(t, 'statement'));
  reflectQuestionNarration().forEach(t => add(t, 'question'));

  SCENARIOS.forEach(sc => add(sc.context, 'statement'));

  questionBank.forEach(q => {
    add(q.questionText, 'question');
    add(q.hint1, 'thinking');
    add(q.hint2, 'thinking');
  });

  return phrases;
}

async function syncMap() {
  const phrases = buildPhrases();
  const audioMap = {};
  let mappedCount = 0;

  for (let i = 0; i < phrases.length; i++) {
    const { text } = phrases[i];
    const slug = slugify(text.toLowerCase(), { replacement: '_', lower: true, strict: true }).slice(0, 80);
    const filename = `${slug}_${i}.mp3`;
    const filePath = join(AUDIO_DIR, filename);

    if (existsSync(filePath)) {
      audioMap[text] = `/assets/audio/${filename}`;
      mappedCount++;
    }
  }

  const content = `// Auto-generated by scripts/build_audio_map.js — DO NOT edit by hand.\nexport const audioMap = ${JSON.stringify(audioMap, null, 2)};\n`;
  await writeFile(AUDIO_MAP_PATH, content);
  console.log(`Synced audioMap.js with ${mappedCount}/${phrases.length} pre-generated MP3 files.`);
}

syncMap().catch(console.error);
