import { writeFile, mkdir } from 'fs/promises';
import { existsSync } from 'fs';
import dotenv from 'dotenv';
import slugify from 'slugify';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { questionBank } from '../src/data/questionBank.js';
import { SCENARIOS } from '../src/data/numberData.js';
import {
  wonderNarration,
  getStoryNarration,
  simulateStationNarration,
  simulateFeedbackNarration,
  praisePhrases,
  playPhaseNarration,
  reflectQuestionNarration
} from '../src/utils/narration.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

dotenv.config({ path: '.env.local' });

const VOICE_ID = 'Xb7hH8MSUJpSbSDYk0k2';
const MODEL_ID = 'eleven_multilingual_v2';

const voiceSettings = {
  celebration: { stability: 0.12, similarity_boost: 0.45, style: 0.75, use_speaker_boost: true },
  encouragement: { stability: 0.16, similarity_boost: 0.50, style: 0.65, use_speaker_boost: true },
  question: { stability: 0.20, similarity_boost: 0.55, style: 0.55, use_speaker_boost: true },
  emphasis: { stability: 0.16, similarity_boost: 0.50, style: 0.60, use_speaker_boost: true },
  thinking: { stability: 0.24, similarity_boost: 0.60, style: 0.35, use_speaker_boost: true },
  statement: { stability: 0.20, similarity_boost: 0.55, style: 0.50, use_speaker_boost: true },
  instruction: { stability: 0.20, similarity_boost: 0.55, style: 0.50, use_speaker_boost: true }
};

// Build the full phrase list programmatically from narration.js (all static UI
// copy, including Simulate station intros/feedback/resets), numberData.js
// SCENARIOS (spoken via speak(getScenario(id).context) when switching real-world
// scenarios in Station D), and questionBank.js (question text + both hints).
// Note: several speak() calls in SimulatePhase.jsx use template literals with
// dynamic values (preset value readouts, plot/duel results, ladder
// praise) — those vary per interaction and fall back to the live ElevenLabs
// API at runtime, same as any other dynamic content this module narrates.
function buildPhrases() {
  const phrases = [];
  const seen = new Set();
  const add = (text, style) => {
    if (!text || seen.has(text)) return; // de-duplicate exact repeats (e.g. praise phrases)
    seen.add(text);
    phrases.push({ text, style });
  };

  wonderNarration().forEach(t => add(t, 'question'));
  getStoryNarration().forEach(t => add(t, 'statement'));
  simulateStationNarration().forEach(t => add(t, 'instruction'));
  simulateFeedbackNarration().forEach(t => add(t, 'encouragement'));
  praisePhrases().forEach(t => add(t, 'celebration'));
  playPhaseNarration().forEach(t => add(t, 'statement'));
  reflectQuestionNarration().forEach(t => add(t, 'question'));

  SCENARIOS.forEach(sc => add(sc.context, 'statement'));

  questionBank.forEach(q => {
    add(q.questionText, 'question');
    add(q.hint1, 'thinking');
    add(q.hint2, 'thinking');
  });

  return phrases;
}

const phrases = buildPhrases();

const API_KEY = process.env.VITE_ELEVENLABS_API_KEY;
const AUDIO_DIR = join(__dirname, '..', 'public', 'assets', 'audio');
const AUDIO_MAP_PATH = join(__dirname, '..', 'src', 'utils', 'audioMap.js');

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function generateAudio() {
  if (!API_KEY) {
    console.error('Error: VITE_ELEVENLABS_API_KEY not found in .env.local');
    process.exit(1);
  }

  if (!existsSync(AUDIO_DIR)) {
    await mkdir(AUDIO_DIR, { recursive: true });
  }

  const audioMap = {};

  for (let i = 0; i < phrases.length; i++) {
    const { text, style } = phrases[i];
    const settings = voiceSettings[style] || voiceSettings.statement;
    const slug = slugify(text.toLowerCase(), { replacement: '_', lower: true, strict: true }).slice(0, 80);
    const filename = `${slug}_${i}.mp3`;
    const filePath = join(AUDIO_DIR, filename);

    try {
      console.log(`Generating ${i + 1}/${phrases.length}: "${text.slice(0, 60)}..." (${style})...`);

      const response = await fetch(
        `https://api.elevenlabs.io/v1/text-to-speech/${VOICE_ID}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'xi-api-key': API_KEY
          },
          body: JSON.stringify({
              text,
              model_id: MODEL_ID,
              voice_settings: settings
            })
        }
      );

      if (!response.ok) {
        throw new Error(`API request failed: ${response.status} ${response.statusText}`);
      }

      const buffer = await response.arrayBuffer();
      await writeFile(filePath, Buffer.from(buffer));
      audioMap[text] = `/assets/audio/${filename}`;
      console.log(`Saved to ${filePath}`);

      await sleep(500);
    } catch (err) {
      console.error(`Error generating "${text}":`, err);
    }
  }

  const audioMapContent = `// Auto-generated by scripts/generate_audio.js — DO NOT edit by hand.\nexport const audioMap = ${JSON.stringify(audioMap, null, 2)};`;
  await writeFile(AUDIO_MAP_PATH, audioMapContent);
  console.log('audioMap.js generated successfully!');
  console.log(`Done! Generated ${Object.keys(audioMap).length} audio files.`);
}

generateAudio().catch(console.error);
